[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["alu <alu@byteberry.net>"]
edition = "2018"

[dependencies]
regex = "1.4.2"
itertools = "0.9.0"
raster = "0.2.0"
lazy_static = "1.4.0"

[workspace]
members = [
    "bootstrapper"
]